services:
  db:
    image: postgres:13
    ports:
      - 4321:5432
    environment:
      POSTGRES_PASSWORD: xmtp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5